<?php

  /*
callback functions to switch between different datasets
  */

function AnnualToAnnual($dest, $ptk, $stk) {
  // stub
}

function AnnualToMonthly($dest, $ptk, $stk) {
  // stub
}

function AnnualToWeekly($dest, $ptk, $stk) {
  // stub
}

function MonthlyToAnnual($dest, $ptk, $stk) {
  // stub
}

function MonthlyToMonthly($dest, $ptk, $stk) {
  // stub
}

function MonthlyToWeekly($dest, $ptk, $stk) {
  // stub
}

function WeeklyToAnnual($dest, $ptk, $stk) {
  // stub
}

function WeeklyToMonthly($dest, $ptk, $stk) {
  // stub
}

function WeeklyToWeekly($dest, $ptk, $stk) {
  // stub
}

function DefaultConversion($dest, $ptk, $stk) {
  // stub
}
