<?php

include_once 'data_snapshots.fields.data_snapshot.inc';
include_once 'data_snapshots.field_groups.inc';
include_once 'data_snapshots.ds.inc';
include_once 'data_snapshots.import.inc';
include_once 'data_snapshots.feeds_tamper_default.inc';
include_once 'data_snapshots.switch_callbacks.inc';

/**
 * Implements hook_ctools_plugin_api().
 *
 * This is necessary for our field_group settings to work.
 */
function data_snapshots_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == 'field_group' && $api == 'field_group') {
    return array('version' => 1);
  }    
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => 1);
  }
  if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
    return array("version" => "2");
  }
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
}

/*
 * Implements hook_node_info().
 *
 * Here is where we declare the contents types that our module defines.
 */
function data_snapshots_node_info() {
  $items = array(
    'data_snapshot' => array(
      'name' => t('Data Snapshot'),
      //NOTE: the setting for 'base' seems to determine (at least) two things:
      //      (a) the prefix for forming the names of hook functions for this
      //          content type; e.g. if 'base' => 'BASE', then we can
      //          implement BASE_load(), BASE_view(), etc, and Drupal will
      //          call them when dealing with a node of this content type
      //      (b) whether or not this content type appears in the list of
      //          editable content types in the admin menu at
      //            Administration >> Structure >> Content Types
      //          Note however, that regardless of whether this content type
      //          appears in the list, you can always navigate directly
      //          to the URL for editing it at
      //             admin/structure/types/manage/data-snapshot-data-source
      'base' => 'data_snapshots',
      'description' => t('Content type for Data Snapshots'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_insert()
 */
// Q: Why is guid '???'?
// Q: What are the translations of these fields?
// Q: What does hook_insert do?
function data_snapshots_insert($node) {
  if ($node->type == "data_snapshot") {
    db_insert('data_snapshots')
      ->fields(array(
        'nid'  => $node->{'nid'},
        'guid' => "???",
        'dsmn' => $node->{'field_ds_dsds_mn'}['und'][0]['value'],
        'ptk'  =>$node->{'field_ds_ptk'}['und'][0]['value'],
        'stk'  =>$node->{'field_ds_stk'}['und'][0]['value']
      ))
      ->execute();
  }
}

/**
 * Implements hook_update()
 */
// Q: Why is guid '???'?
// Q: What are the translations of these fields?
// Q: What does hook_update do?
function data_snapshots_update($node) {
  if ($node->type == "data_snapshot") {
    db_update('data_snapshots')
      ->fields(array(
        'guid' => "???",
        'dsmn' => $node->{'field_ds_dsds_mn'}['und'][0]['value'],
        'ptk'  =>$node->{'field_ds_ptk'}['und'][0]['value'],
        'stk'  =>$node->{'field_ds_stk'}['und'][0]['value']
      ))
      ->condition('nid', $node->{'nid'})
      ->execute();
  }
}

/**
 * Implements hook_form()
 */
// Q: What does hook form do?
// Q: WHat is node_content_form?
function data_snapshots_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_theme()
 */
// Probably need to remove this and move this functionality back to display suite
function data_snapshots_theme($existing, $type, $theme, $path) {
  return array (
    'ds_2col_stacked__node_data_snapshot_full' => array(      # when theming nodes of type data_snapshot,
      'template' => 'templates/ds-2col-stacked--node-data-snapshot-full',     #     use data-snapshot.tpl.php 
    ),
    'field__field_ds_disimg__data_snapshot' => array(
      'template' => 'templates/field--field_ds_disimg--data-snapshot',
    ),
    'field__field_ds_dloads__data_snapshot' => array(
      'template' => 'templates/field--field_ds_dloads--data-snapshot',
    ),
    'field__field_ds_dsds_mn__data_snapshot' => array(
      'template' => 'templates/field--field_ds_dsds_mn--data-snapshot',
    ),
    'node__data_snapshot' => array(      # when theming nodes of type data_snapshot,
      'template' => 'templates/data-snapshot',     #     use data-snapshot.tpl.php 
    ),
    'data-snapshot-sidebar' => array(          # when theme() is called like
      'template' => 'templates/data-snapshot-sidebar',   #   theme('data-snapshot-sidebar',...),
      'variables' => array(                    #   use data-snapshot-sidebar.tpl.php
        'data_set_name' => NULL,               #   along with these variables
        'data_set_number' => NULL
      )
    ),
  );
}

/*
 * Implements hook_load()
 *
 * Note that we don't actually need this, at the moment, but I'm leaving it in here commented
 * out as a reminder that we can use it if/when it turns out we need to.  hook_load() allows
 * us to arrange for arbitrary things to happen each time a node of one of our content types
 * is loaded; we can modify the $node object here to insert whatever we want (within reason).
 *
function data_snapshots_load($nodes) {
  //dsm("***********   data_snapshots_load   *************************\n");
  //dsm($nodes);
  //NOTE: hook_load() does not (need to) return anything
}
*/

/*
 * I'm really not sure what the correct way to fetch a node field value is,
 * but this seems to work.  There has to be a better way, though.
 */
// Q: This is for the following view I think??
function _get_field_value($node, $field) {
  $q = field_get_items('node', $node, $field);
  return $q[0]['value'];
}


/**
 * Implements hook_view()
 *
 * This gets called before rendering any nodes defined in our hook_node_info() above for
 * which base=data_snapshots.  We can use this to modify the node object before it is
 * rendered.
 *
 * This funtion should ALWAYS return $node!!!
 *
 * What the @#$%&*# !!!???
 *
 *   The mere presence of this hook apparently changes the structure of the contents
 *   of the $node object that gets passed to the template file.  When this hook is
 *   NOT present, field values are available like:
 *       $node->{'field_ds_year'}['und'][0]['value']
 *   When this hook is present, though, the 'und' layer disappears, so the same field
 *   becomes
 *       $node->{'field_ds_year'}[0]['value']
 *   This happens regardless of what this function (data_snapshots_view) does --
 *   in particular, simply creating a data_snapshots_view function that just
 *   does "return $node" causes this.
 *
 *   Note, however, that this is true only for the $node object that
 *   gets passed to the *.tpl.php, however.  The $node object passed to
 *   data_snapshots_view() here DOES have the 'und' layer.
 *
 * UPDATE:
 *
 *   Well, it seems that making a few other changes, such as setting
 *   some fields in $node->content below, and adding another tpl.php
 *   for theming that content, caused the 'und' level to reappear.
 *
 *   The moral of this story is that whenever you change anything
 *   here, better re-examine how everything looks and fix anything
 *   that breaks!
 *
 *   Isn't Drupal wonderful!!
 *
 * ANOTHER UPDATE:
 *
 * Holy shit!  Simply including "dsm($node)" at the top of
 * data_snapshots_view() changes the structure of the $node object
 * that is available to the template file!!!
 */
// Q: what do these fields translate to?
// Q: figure out if there is a better place for the drupal_add_[css|js]?
// Q: I think there are a few more parameters which help with the previous function and caching?
function data_snapshots_view($node, $view_mode) {
  drupal_add_css(drupal_get_path('module', 'data_snapshots') . "/css/data-snapshots.css");
  drupal_add_css(drupal_get_path('module', 'data_snapshots') . "/js/jquery-ui/jquery-ui-1.10.3/themes/base/jquery.ui.all.css");

  drupal_add_js(drupal_get_path('module', 'data_snapshots') . "/js/data_snapshots.js",
                array('scope' => 'header', 'group' => JS_DEFAULT, 'weight' => 1001));
  drupal_add_js(drupal_get_path('module', 'data_snapshots') . "/js/bootstrap.js",
                array('scope' => 'header', 'group' => JS_DEFAULT, 'weight' => 1001));
  drupal_add_js("if (jQuery !== undefined) { jQuery_old = jQuery; }",
                array('type' => 'inline', 'scope' => 'header', 'group' => JS_DEFAULT, 'weight' => 1002));
  drupal_add_js(drupal_get_path('module', 'data_snapshots') . "/js/jquery-ui/jquery-ui-1.10.3/jquery-1.9.1.js",
                array('scope' => 'header', 'group' => JS_DEFAULT, 'weight' => 1003));
  drupal_add_js(drupal_get_path('module', 'data_snapshots') . "/js/jquery-ui/jquery-ui-1.10.3/ui/jquery-ui.js",
                array('scope' => 'header', 'group' => JS_DEFAULT, 'weight' => 1004));
  drupal_add_js("data_snapshots(jQuery); if (jQuery_old !== undefined) { jQuery = jQuery_old; }",
                  array('type' => 'inline', 'scope' => 'header', 'group' => JS_DEFAULT, 'weight' => 1005));

  $dsds_mn = _get_field_value($node, 'field_ds_dsds_mn');
  $init_ptk = _get_field_value($node, 'field_ds_ptk');
  $init_stk = _get_field_value($node, 'field_ds_stk');
  if ($dsds_mn) {
    if ($node->type == "data_snapshot" && $view_mode == "full") {
      $dataset_nid = db_select('field_data_field_dssds_machine_name', 'f')
        ->condition('field_dssds_machine_name_value', $dsds_mn)
        ->fields('f', array('entity_id'))
        ->execute()
        ->FetchField();
      if ($dataset_nid != FALSE) {
        $node->{'dataset_node'} = node_load($dataset_nid);
      }

      $rows = db_select('data_snapshots', 'ds')
        ->fields('ds', array('nid','ptk','stk'))
        ->condition('dsmn', $dsds_mn)
        ->orderBy('ds.ptk', 'ASC')
        ->orderBy('ds.stk', 'ASC')
        ->execute()
        ->fetchAll();
      $snapshots = array();
      if (!empty($rows)) {
        $ptk = null;
        $ptks = array();
        foreach ($rows as $row) {
          if ($row->{'ptk'} != $ptk) {
            $snapshots[$row->{'ptk'}] = array();
            $ptk = $row->{'ptk'};
            $ptks[] = $ptk;
          }
          $snapshots[$ptk][] = $row->{'stk'};
        }
      }

      // list of themes
      $themes = array();
      $theme_lookup = array();// lookup table
      $data_sources = array();// initialized here to store keys
      $theme_taxonomy_name = 'data_snapshots_themes';
      $query = db_select('taxonomy_term_data', 'ttd')
        ->fields('ttd', array('tid','name'))
	->orderBy('name');
      $query->leftJoin('taxonomy_vocabulary', 'tv', '(ttd.vid = tv.vid)');
      $query->condition('tv.machine_name', $theme_taxonomy_name);
      $rows = $query->execute()
	->fetchAll();
      if (!empty($rows)) {
        foreach ($rows as $row) {
	  $themes[] = $row->name;
	  $theme_lookup[$row->tid] = $row->name;
	  $data_sources[$row->name] = array();
        }
      }

      $query = db_select('field_data_field_dssds_themes', 'th')
	->fields('th', array('field_dssds_themes_tid'));
      $query->join('field_data_field_dssds_official_name', 'ona', '(th.entity_id = ona.entity_id)');
      $query->join('field_data_field_dssds_machine_name', 'mna', '(th.entity_id = mna.entity_id)');
      $query->fields('ona', array('field_dssds_official_name_value'))
	->fields('mna', array('field_dssds_machine_name_value'))
	->orderBy('field_dssds_official_name_value');
      $rows = $query->execute()
        ->fetchAll();
      if (!empty($rows)) {
        foreach ($rows as $row) {
	  $theme = $theme_lookup[$row->field_dssds_themes_tid];
	  $data_source = array();
	  $data_source['oname'] = $row->field_dssds_official_name_value;
	  $data_source['mname'] = $row->field_dssds_machine_name_value;
          $data_sources[$theme][] = $data_source;
        }
      }

      $settings = array(
        'snapshots' => array(
          'dsmn' => $dsds_mn,
          'p' => $ptks,
          's' => $snapshots,
	  'init_ptk' => $init_ptk,
	  'init_stk' => $init_stk,
        ),
	'themes' => $themes,
	'datasources' => $data_sources,
	'init_theme' => (array_key_exists('theme', $_REQUEST)) ? $_REQUEST['theme'] : null,
      );


      drupal_add_js(array('data_snapshots' => $settings), 'setting');
      // So now, we can access the $snapshots array from JS in the page as:
      //      Drupal.settings.data_snapshots.snapshots
    }
  }
  return $node;
  //NOTE: hook_view MUST return $node
}

// Q: What does this do?
function data_snapshots_node_type_insert($content_type) {

  if ($content_type->type == 'data_snapshot') {
    // following code block taken from features module

    // Load all the existing fields and instance up-front
    $existing_fields = field_info_fields();
    $existing_instances = field_info_instances();

    foreach (data_snapshots_fields_data_snapshot() as $field) {
      // Create or update field.
      $field_config = $field['field_config'];
      if (isset($existing_fields[$field_config['field_name']])) {
        $existing_field = $existing_fields[$field_config['field_name']];
        if ($field_config + $existing_field != $existing_field) {
          field_update_field($field_config);
        }
      }
      else {
        field_create_field($field_config);
        $existing_fields[$field_config['field_name']] = $field_config;
      }

      // Create or update field instance.
      $field_instance = $field['field_instance'];
      if (isset($existing_instances[$field_instance['entity_type']][$field_instance['bundle']][$field_instance['field_name']])) {
        $existing_instance = $existing_instances[$field_instance['entity_type']][$field_instance['bundle']][$field_instance['field_name']];
        if ($field_instance + $existing_instance != $existing_instance) {
          field_update_instance($field_instance);
        }
      }
      else {
        field_create_instance($field_instance);
        $existing_instances[$field_instance['entity_type']][$field_instance['bundle']][$field_instance['field_name']] = $field_instance;
      }
    }
  }

  // sets up alias for data snapshots
  variable_set('pathauto_node_data_snapshot_pattern', 'data-snapshot/[node:field_ds_dsds_mn]-[node:field_ds_ptk]-[node:field_ds_stk]');
}
/**
 * Implements hook_menu().
 */
// Q: what exactly is being put into the menu?
function data_snapshots_menu() {

  $items['data-snapshots/ajax'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Callback Only',
    'page callback' => '_data_snapshots_datasource_ajax',
    'page arguments' => array(t('The menu entry for this page is of type MENU_CALLBACK, so it provides only a path but not a link in the menu links, but it is the same in every other way to the simplest example.')),
    'access callback' => TRUE,
  );

  // TODO: combine these two items into one, with a paramater to determine the final callback used
  $items['data-snapshots/snapshots/ajax'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Callback Only',
    'page callback' => '_data_snapshots_snapshot_ajax',
    'page arguments' => array(t('The menu entry for this page is of type MENU_CALLBACK, so it provides only a path but not a link in the menu links, but it is the same in every other way to the simplest example.')),
    'access callback' => TRUE,
  );

  return $items;
}

/*
TODO: pass both machine names to this, get all info in one query
*/
function _data_snapshots_get_frequency($machine_name) {
  $query = db_select('taxonomy_term_data', 'ttd')
    ->fields('ttd', array('name'));
  $query->leftJoin('field_data_field_dssds_image_frequency', 'fdif', 'fdif.field_dssds_image_frequency_tid = ttd.tid');
  $query->leftJoin('field_data_field_dssds_machine_name', 'fdmn', 'fdmn.entity_id = fdif.entity_id');
  $query->condition('fdmn.field_dssds_machine_name_value', $machine_name);
  return $query->execute()
    ->FetchField();
}

function _data_snapshots_get_callback($cur_freq, $new_freq, $cur_name, $new_name) {
  $custom_freq = 'Custom';
  if ($cur_freq == $custom_freq) {
    $cur_freq = $cur_freq . $cur_name;
  }
  if ($new_freq == $custom_freq) {
    $new_freq = $new_freq . $new_name;
  }
  $callback = $cur_freq . 'To' . $new_freq;

  if (function_exists($callback)) {
    return $callback;
  } else {
    return 'DefaultConversion';
  }
}

function _data_snapshots_snapshot_ajax() {
  $result = db_select('data_snapshots', 'ds')
    ->fields('ds', array('nid'))
    ->condition('dsmn', $_POST['dsmn'])
    ->condition('ptk', $_POST['ptk'])
    ->condition('stk', $_POST['stk'])
    ->execute()
    ->fetchAssoc();

  $new_ds_node = node_load($result['nid']);
  $result['body_html'] = render(field_view_field('node', $new_ds_node, 'body'));
  $result['download_html'] = render(field_view_field('node', $new_ds_node, 'field_ds_dloads'));

  $ds_fields = ds_get_fields('node');
  $ds_permalink_field = $ds_fields['data_snapshot_permalink'];
  $ds_permalink_field['entity'] = $new_ds_node;
  $result['permalink_html'] = ds_render_code_field($ds_permalink_field);

  drupal_json_output($result);
  exit();
}

//select nid, body_value from data_snapshots JOIN field_data_body ON entity_id=nid where dsmn="usdm" AND ptk="2000" AND stk="01-04" ;
function _data_snapshots_datasource_ajax() {
  // Get type of dataset from machine name
  $current_frequency = _data_snapshots_get_frequency($_POST['current']);
  $new_frequency = _data_snapshots_get_frequency($_POST['new']);

  // Get conversion callback
  $callback = _data_snapshots_get_callback($current_frequency, $new_frequency, $_POST['current'], $_POST['new']);

  $dataset_nid = db_select('field_data_field_dssds_machine_name', 'f')
    ->condition('field_dssds_machine_name_value', $_POST['new'])
    ->fields('f', array('entity_id'))
    ->execute()
    ->FetchField();

  // Serve it back up
  if ($current_frequency != FALSE && $new_frequency != FALSE) {
    $obj = array(
		 'request' => $_POST,
		 'current_frequency' => $current_frequency,
		 'new_frequency' => $new_frequency,
		 'callback' => $callback($_POST['new'], $_POST['ptk'], $_POST['stk']),
		 'node' => node_load($dataset_nid),
		 );
  } else {
    $obj = array(
		 'request' => $_POST,
		 'error' => 'freq not found',
		 );
  }
  drupal_json_output($obj);
  exit();
}

// Keeping this function for now as a reference. Will delete later.
//   jrf.
function _data_snapshots_ajax() {
  global $user;
  $received = file_get_contents("php://input");
  $json = json_decode($received, TRUE);

  //
  // Assume that we received a json object whose "guid" property is a guid from
  // the feeds_item table.  Look up the nid corresponding to it.
  //
  // select entity_id from feeds_item where guid='droutlook-2013-06-18' ;
  $nid = db_select('feeds_item', 'fi')
    ->condition('guid', $json['guid'])
    ->fields('fi', array('entity_id'))
    ->execute()
    ->FetchField();

  //
  // And serve back the contents of that nid's node as the response
  //
  if ($nid != FALSE) {
    // we don't technically need to load the whole node here -- optimize later to directly query
    // only the relevant fields tables
    $node = node_load($nid);
    $obj = array(
      'user' => $user,
      'request' => $json,
      'node' => array(
        'nid' => $nid,
        'stk' => $node->{'field_ds_stk'}['und'][0]['value'],
        'ptk' => $node->{'field_ds_ptk'}['und'][0]['value'],
        'img' => $node->{'field_ds_disimg'}['und'][0]['url'],
        'about' => $node->{'body'}['und'][0]['value']
        )
    );
  } else {
    $obj = array(
      'user' => $user,
      'request' => $json,
      'error' => 'node not found'
    );
  }
  drupal_json_output($obj);
  exit();
}
