#! /bin/bash

# import USDM data set node
drush ne-import < dev/data-set-usdm.json 
drush ne-import < dev/data-set-ghcntempm.json
drush ne-import < dev/data-set-ghcntempm-annual.json
drush ne-import < dev/data-set-spc_severe.json
#drush ne-import < data-snapshot-usdm-2000-01-04.json

drush -y en feedsdrush ; drush cc all
drush fim data_snapshot_importer http://dev.nemac.org/datasnapshots-images/images/html/usdm/feed.csv
drush fim data_snapshot_importer http://dev.nemac.org/datasnapshots-images/images/html/ghcntemp/feed.csv
drush fim data_snapshot_importer http://dev.nemac.org/datasnapshots-images/images/html/spc_severe/feed.csv
