<?php
/**
 * @file
 * Code for the DSS Data Source Export feature.
 */

include_once 'data_snapshots_data_source.features.inc';

function data_snapshots_data_source_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['full']['custom settings'] = TRUE;
  $entity_info['node']['view modes']['teaser']['custom settings'] = TRUE;
  $entity_info['node']['view modes']['search_result']['custom settings'] = TRUE;

  $entity_info['node']['view modes']['nf_related_content_teaser'] = array(
                                                                          'label' => 'NF Related Content Teaser',
                                                                          'custom settings' => TRUE,
                                                                          );
  $entity_info['node']['view modes']['nf_category_listing'] = array(
                                                                    'label' => 'NF Category Listing',
                                                                    'custom settings' => TRUE,
                                                                    );
  $entity_info['node']['view modes']['short_teaser'] = array(
                                                             'label' => 'Short Teaser',
                                                             'custom settings' => TRUE,
                                                             );
  $entity_info['node']['view modes']['tiny_teaser'] = array(
                                                            'label' => 'Tiny Teaser',
                                                            'custom settings' => TRUE,
                                                            );
}

function data_snapshots_data_source_node_type_insert($content_type) {
  if ($content_type->type == 'data_snapshot_data_source') {
    // sets up alias for data snapshots
    variable_set('pathauto_node_data_snapshot_data_source_pattern', 'data-snapshot/data-source-[node:title]');
  }
}
