#! /bin/bash

# import data set nodes

# reload data set node content saved by "si" script...
drush scr dev/retidify-datasets-json
drush ne-import < dev/datasets-retids.json

#( cd dev/data-sets ; ./make_node_jsons )
#drush ne-import < dev/data-sets/node_json/averagetemp-monthly-cmb.node.json
#drush ne-import < dev/data-sets/node_json/tempanomaly-annual-nnvl.node.json
#drush ne-import < dev/data-sets/node_json/usdroughtmonitor-weekly-ndmc.node.json
#drush ne-import < dev/data-sets/node_json/droughtoutlook-monthly-cpc.node.json
#drush ne-import < dev/data-sets/node_json/tempanomaly-monthly-nnvl.node.json
#drush ne-import < dev/data-sets/node_json/oisst-daily-cdr.node.json	      
#drush ne-import < dev/data-sets/node_json/totalprecip-monthly-cmb.node.json
#drush ne-import < dev/data-sets/node_json/probseverewx-dayofyear-spc.node.json

#drush ne-import < data-snapshot-usdm-2000-01-04.json
#drush -y en feedsdrush ; drush cc all
#drush fim data_snapshot_importer http://datasnapshots-images.nemac.com/usdm/feed.csv
#drush fim data_snapshot_importer http://datasnapshots-images.nemac.com/ghcntemp/feed.csv
#drush fim data_snapshot_importer http://datasnapshots-images.nemac.com/spc_severe/feed.csv

drush variable-set --yes data_snapshots_import_url "http://107.20.157.228/Images/feed.csv"

echo "importing nodes now, this might take a while"

drush scr dev/run_import.php

echo "importing done."
